name: Release Plugin
on:
  release:
    types: [published] # Trigger only when a release is published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP file
        run: |
          zip -r reserve-mate.zip . -x ".git/*" ".github/*"

      - name: Upload ZIP as release asset (gh CLI)
        run: gh release upload ${{ github.event.release.tag_name }} reserve-mate.zip
        env:
          GH_TOKEN: ${{ secrets.repoToken }}
